language: node_js
node_js:
  - 'stable'
install:
  - npm install
script:
  - npm run package:chromium
  - npm run package:firefox
before_deploy:
  - git tag ${XBS_VERSION}
deploy:
  provider: releases
  # â‹®
  file:
    - 'dist/xbrowsersync_${XBS_VERSION}_chromium.zip'
    - 'dist/xbrowsersync_${XBS_VERSION}_firefox.zip'
  on:
    all_branches: true
    tags: true
  prerelease: true
  skip_cleanup: true
  token: ${github_api_key}
branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+.*$/
